# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['status_of_cameras_GUI.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icon.ico', '.'),
        ('ico/*', 'ico'),
        ('camera_cache.json', 'data'),
        ('prime_camera_sn.py', '.'),
        ('goprolist_and_start_usb.py', '.'),
        ('utils.py', '.'),
        ('goprolist_usb_activate_time_sync_record.py', '.'),
        ('stop_record.py', '.'),
        ('date_time_sync.py', '.'),
        ('set_preset_0.py', '.'),
        ('set_video_mode.py', '.'),
        ('read_and_write_all_settings_from_prime_to_other.py', '.'),
    ],
    hiddenimports=[
        'PyQt5',
        'requests',
        'zeroconf',
        'zeroconf._utils.ipaddress',
        'zeroconf._services.info',
        'zeroconf._core',
        'zeroconf._engine',
        'zeroconf._listener',
        'zeroconf._handlers',
        'zeroconf._handlers.answers',
        'zeroconf._handlers.browser',
        'zeroconf._handlers.cache',
        'zeroconf._handlers.incoming',
        'zeroconf._handlers.outgoing',
        'zeroconf._handlers.query',
        'zeroconf._handlers.record_manager',
        'zeroconf._updates',
        'zeroconf._services.browser',
        'zeroconf._services.registry',
        'zeroconf._services.info',
        'zeroconf._utils',
        'zeroconf._utils.name',
        'zeroconf._utils.time',
        'zeroconf._utils.net',
        'concurrent.futures',
        'json',
        'logging',
        'datetime',
        'pathlib',
        'pkg_resources',
        'subprocess',
        'threading',
        'time',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='status_of_cameras_GUI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico'
)
